### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by bchurchill** [egasimus/xmonad-equalspacing#1]
Thank you for developing this.  This problem has been bugging me for a while, but I never looked into it and just found your reddit link.  Anyway, I tried compiling this and got some errors, which look superficial, but I don't know how to fix them off the top of my head.

```
EqualSpacing.hs:38:31:
    Couldn't match expected type `X11-1.5.0.1:Graphics.X11.Xlib.Types.Rectangle'
                with actual type `Rectangle'
    In the return type of a call of `shrinkScreen'
    In the second argument of `($)', namely
      `shrinkScreen
         eqsp ((length $ integrate' $ stack workspace) - 1) screen'
    In the expression:
      runLayout workspace
      $ shrinkScreen
          eqsp ((length $ integrate' $ stack workspace) - 1) screen

EqualSpacing.hs:41:15:
    Couldn't match expected type `X11-1.5.0.1:Graphics.X11.Xlib.Types.Rectangle'
                with actual type `Rectangle'
    Expected type: (a, Rectangle)
                  -> (a, X11-1.5.0.1:Graphics.X11.Xlib.Types.Rectangle)
      Actual type: (a, Rectangle) -> (a, Rectangle)
    In the first argument of `map', namely
      `(second $ shrinkWindow eqsp ((length $ integrate' stck) - 1))'
    In the expression:
      map
        (second $ shrinkWindow eqsp ((length $ integrate' stck) - 1))
        windows
```

**Comment by egasimus** [comment]
I'm afraid I don't know what might be causing that. Mismatched dependencies perhaps, or different compiler directives at the top of your `xmonad.hs`? I have to admit that (regrettably) I never really became fluent in Haskell and have given myself a break from trying to properly figure it out -- at least for the time being.

On a side note, I stuck to xmonad for the longest time but after I got my laptop stolen I had a brief stint with Gnome3 and now now migrated to awesomewm instead -- it's scriptable in Lua which is much easier to wrap your head around (it's almost JavaScript), and in my experience has been just as stable and lightweight as xmonad. Although I'm not sure yet if it has layout composability so getting nice gaps was again non-trivial.

Thanks for your interest and sorry for the late reply,
Adam

**Comment by bchurchill** [comment]
Thanks for letting me know!  If I ever figure out what fixes it I'll
report back.

**Comment by bchurchill** [comment]
Turns out I had two versions of the X11 haskell library installed.  No idea how that happened -- I've never touched those packages on debian stable.  After removing the _newer_ one which wasn't being used, I was left with 1.5.0.1 which worked.
